<?php require __DIR__ . '/../headerlogin.phtml' ?>
<?php foreach ($newsListing as $news): ?>
    <div class="alert alert-info">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h4 class="alert-heading">
            <h3><?= $news['headline'] ?></h3>
        </h4>
        <?= $news['message'] ?>
    </div> <!-- /.alert -->
<?php endforeach;

$wartung = DB::queryFirstRow("SELECT wartungsmodus FROM config WHERE id=%s",'1');
if($wartung['wartungsmodus'] == 1){?>
    <div class="alert alert-info">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h4 class="alert-heading">
            <h3><?= _('Wartungsmodus Aktiv') ?></h3>
        </h4>
        <?= _('Login ist nur für Administratoren möglich!') ?>
    </div>

<?php }
?>
<div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Ecast</b>Control Panel</a>
      </div>
      <div class="login-box-body">
        <p class="login-box-msg"></p>
        <form action="/login" method="post">
          <div class="form-group has-feedback">
            <input type="text" id="username" name="username" class="form-control" placeholder="Usuario">
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" id="password" name="password" class="form-control" placeholder="Password">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
            </div>
          </div>
        </form>
      </div>
    </div>

<?php require __DIR__ . '/../footerlogin.phtml' ?>