<?php require __DIR__ . '/../headerlogin.phtml' ?>
<div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Ecast</b>Control Panel</a>
      </div>
      <div class="login-box-body">
        <p class="login-box-msg"></p>
        <form action="/login" method="post">
          <div class="form-group has-feedback">
            <input type="text" id="username" name="username" class="form-control" placeholder="Usuario">
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" id="password" name="password" class="form-control" placeholder="Password">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
            </div>
          </div>
        </form>
      </div>
    </div>

<?php require __DIR__ . '/../footerlogin.phtml' ?>