<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Ecast Control Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/panel.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/skins/_all-skins.min.css">

    <!-- JS -->

    <!-- SET UP AXUPLOADER-->
    <script type="text/javascript" src="/js/ajaxupload-min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/msgGrowl.js"></script>
</head>
<body class="hold-transition login-page">