<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 4.0.0
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>

<script>
    $(function() {                       // On DOM ready
        $('#myModal').modal('show');     // Show the modal
    });
</script>

<div class="modal fade" id="myModal">
    <form action="/station/changeowner" method="post">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3><?php echo _('Stream einen neuen Kunden zuordnen'); ?></h3>
        </div>
        <div class="modal-body">

            <div class="controls">
                <select id="select01" name="ownerchange">
                    <?php
                    $results = DB::query("SELECT * FROM accounts WHERE usr_grp=%s", 'user');
                    foreach ($results as $row) {
                        echo ' <option value=' . $row['id'] . '>' . $row['kundennummer'] . ' ' . $row['vorname'] . ' ' . $row['nachname'] . ' ' . "</option>";
                    }
                    ?>
                </select>
            </div>
        </div>
        <div class="modal-footer">
            <input type="submit" name="updateUser" class="btn btn-primary" value="<?php echo _('Stream zuordnen'); ?>" />
        </div>
    </form>
</div>