<?php require_once __DIR__ . '/../header.phtml' ?>

<header class="main-header"> <a href="/" class="logo"> <span class="logo-mini"><b>A</b>LT</span> <span class="logo-lg"><b>Ecast</b> Control Panel</span> </a>
  <nav class="navbar navbar-static-top" role="navigation"> <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"> <span class="sr-only">Toggle navigation</span> </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span class="hidden-xs">Bienvenido <strong><?php echo $_SESSION['USERNAME']; ?></strong> <i class="fa fa-sign-out"></i> </span> </a>
          <ul class="dropdown-menu">
            <li class="user-footer">
              <div class="pull-right"> <a href="/logout" class="btn btn-default btn-flat">Salir</a> </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="header"><i class="fa fa-home"></i> Home</li>
      <li><a href="/">-Home </a></li>
      <li class="header"><i class="fa fa-users"></i> Stream</li>
      <li><a href="/station/list">-Ver Streams</a></li>
      <li><a href="/station/add">-Crear Stream</a></li>
      <li class="header"><i class="fa fa-users"></i> Usuarios</li>
      <li><a href="/user/list">-Ver Usuarios</a></li>
      <li><a href="/user/register">-Crear Usuario</a></li>
      <li class="header"><i class="fa fa-users"></i> Server</li>
      <li><a href="/server/conf">-Configuracion </a></li>
      <li><a href="/server/license">-Licensia </a></li>
      <li class="header"></li>
      <li class="header"><i class="fa fa-sign-out"></i> Cerrar Session</li>
      <li><a href="/logout">-Salir</a></li>
    </ul>
  </section>
</aside>
