 
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="widget widget-table">
                        <div class="widget-header">
                            <h3>
                                <i class="icon-th-list"></i>
                                <?php echo _('DJ-User'); ?>
                            </h3>
                        </div>
                        <!-- /widget-header -->
                        <div class="widget-content">
                            <table class="table table-striped table-bordered table-highlight" id="example">
                                <thead>
                                <tr>
                                    <th><?php echo _('DJ - Name / (Loginname)'); ?></th>
                                    <th><?php echo _('Benutzerinformation'); ?></th>
                                    <th><?php echo _('Addresse'); ?></th>
                                    <th><?php echo _('Telefon'); ?></th>
                                    <th><?php echo _('Kontakt'); ?></th>
                                    <th><?php echo _('DJ vom Stream'); ?></th>
                                    <th><?php echo _('DJ-Aktiv?'); ?></th>
                                    <th><?php echo _('Einstellungen'); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $results = DB::query("SELECT * FROM accounts WHERE dj_of_user_id=%s AND usr_grp='dj' ", $_SESSION['account_id']);
                                foreach ($results as $row) {

                                        echo "<td>" . $row['dj_name'] .'<br>('. $row['kundennummer'].")</td>";
                                        echo "<td>" . $row['vorname'] . " " . $row['nachname'] . "</td>";
                                        echo "<td>" . $row['street'] .' '.$row['hausnummer'].'<br>'.$row['plz'].' '.$row['ort']."</td> \n";
                                        echo "<td>"._('Phone')." <b>" . $row['telefon'] . "</b><br>"._('Mobile').": <b> " . $row['handy'] . "</b></td>";
                                        echo "<td>"._('Mail').": <b>".$row['mail']."</b><br> "._('Skype:')." <b>".$row['skype']."</td> \n";

                                        echo '<td>';

                                        $eachSC_rel_id = DB::query("SELECT * FROM dj_accounts WHERE dj_accounts_id=%s", $row['id']);
                                        foreach($eachSC_rel_id as $screlrow){
                                            $StreamName = DB::queryFirstRow("SELECT stream_userName FROM sc_rel WHERE id=%s", $screlrow['dj_of_sc_rel_id']);
                                           ?>
                                            <form action="/dj/delStationFormList" method="post">
                                     <button class="btn btn-danger" value="<?= $screlrow['id'] ?>" name="delStream" ><img src="/image/fuge/cross-circle.png"></button>
                                            <?= $StreamName['stream_userName'] ?><br>
                                            </form>
                                            <form action="/dj/selDjPrio" method="post">
                                                <button class="btn btn-success" value="<?php echo $screlrow['id'] ?>" name="djprioSet" ><img src="/image/fuge/server.png"></button>
                                                <?php echo 'DJ-Priorität: '; if(isset($screlrow['dj_prio'])){echo $screlrow['dj_prio']; } ?> <br>
                                            </form>
                                           <?php
                                        }




                                        echo '</td>';




                                        ?>
                                        <td><form action="/dj/list" method="post">
                                            <?php if ($row['is_aktiv'] == '1' ) {?>
                                                <button class="btn btn-danger" value="<?php echo 'is_aktiv.'.$row['id'].'.0' ?>" name="editDjList" ><?= _('Sperren') ?></button>
                                            <?php
                                            }
                                            if ($row['is_aktiv'] == '0') {
                                                ?>
                                                <button class="btn btn-success" value="<?php echo 'is_aktiv.'.$row['id'].'.1' ?>" name="editDjList" ><?= _('Freischalten') ?></button>
                                            <?php
                                            }

                                            ?>




                                            </form>
                                        </td>
                                        <td>
                                            <form action="/dj/list" method="post">
                                                <button class="btn btn-success" value="<?php echo 'djtoStation.'.$row['id'] ?>" name="editDjList" ><img src="/image/fuge/plus-circle.png"></button>
                                                <button class="btn btn-warning" value="<?php echo 'editDj.'.$row['id'] ?>" name="editDjList" ><img src="/image/fuge/pencil.png"></button>
                                                <button class="btn btn-warning" value="<?php echo 'newPass.'.$row['id'] ?>" name="editDjList" ><img src="/image/fuge/key.png"></button>
                                                <button class="btn btn-danger" value="<?php echo 'delDj.'.$row['id'] ?>" name="editDjList" ><img src="/image/fuge/cross-circle.png"></button>
                                            </form>

                                        </td>


                                        <?php
                                        echo '</tr>';
                                }

















































                                ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /widget-content -->
                    </div>
                    <!-- /widget -->
                </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /.container -->
    </div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>