<?php
/**
 *  Ecast
 */
?>

<div class="content-wrapper">
  <section class="content">
    <div class="row">
      <div class="col-xs-6">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"><i class="fa fa-music"></i> Canciones en la lista de Reproduccion</h3>
          </div>
          <div class="box-body table-responsive no-padding">
            <form method="post" action="/archivos/playlist">
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <th>Nombre</th>
                    <th>Tama&ntilde;o</th>
                    <th>Duracion</th>
                    <th>Accion</th>
                  </tr>
                  <?php
                                        $TIMEFUNC = new core\time\time();

                                        $Size ='0';
                                        $TimeSecond = '0';
                                        $mp3titel = DB::query("SELECT * FROM playlist_mp3_rel WHERE playlist_id=%s", $_SESSION['playlistactiv']);
                                        foreach ($mp3titel as $title) {

                                            $mp3 = DB::query("SELECT * FROM mp3 WHERE id=%s", $title['mp3_id']);
                                            foreach ($mp3 as $mp3tit) {
                                                echo '<tr><form action="/archivos/playlist" method="post" >';
                                                echo "<td>".$mp3tit['org_file_titel']."</td> \n";
                                                $MB = $mp3tit['size'] / 1048576;
                                                echo "<td>".round($MB, 2)."MB</td> \n";
                                                echo "<td>".$TIMEFUNC->seconds2Time($mp3tit['playtime'])."</td> \n";
                                                echo '<td><button class="btn btn-warning" name="delTitleFormEditPlaylist" value="'.$title['id'].'">Quitar</button></td>';
                                                echo '</form></tr>';
                                                $Size += $mp3tit['size'];
                                                $TimeSecond += $TIMEFUNC->seconds2TimeDay($mp3tit['playtime']);
                                            }
                                        }
                                        echo '<tr>';
                                        echo "<td></td> \n";
                                        echo "<td>";
                                        $FileSize = new core\file\filesize();
                                        echo $FileSize->format_filesize($Size);
                                        echo "</td> \n";
                                        echo "<td> </td> \n";
                                        echo "<td>";
                                        echo $TIMEFUNC->seconds2Time($TimeSecond);
                                        echo "</td> \n";
                                        echo '</tr>';
                                        ?>
                </tbody>
              </table>
            </form>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"><i class="fa fa-music"></i> Canciones en la Carpeta</h3>
          </div>
          <div class="box-body table-responsive no-padding">
            <form method="post" action="/archivos/playlist">
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <th>Nombre</th>
                    <th>Tama&ntilde;o</th>
                    <th>Duracion</th>
                    <th>Accion</th>
                  </tr>
                  <?php
                                        $results = DB::query("SELECT * FROM mp3_usr_rel WHERE user_id=%s", $_SESSION['account_id']);

                                        foreach ($results as $row) {
                                            $mp3titel = DB::query("SELECT * FROM mp3 WHERE id=%s", $row['mp3_id']);
                                            foreach ($mp3titel as $title) {
                                                echo '<tr><form action="/archivos/playlist" method="post">';
                                                echo "<td>".$title['org_file_titel']."</td> \n";
                                                $MB = $title['size'] / 1048576;
                                                echo "<td>".round($MB, 2)."MB</td> \n";
                                                echo "<td>".$TIMEFUNC->seconds2Time($title['playtime'])."</td> \n";
                                                echo '<td><button class="btn btn-success" value="'. $title['id']  .'" name="addTitleToplst"><img src="/image/fuge/plus-circle.png"></button></td>';
                                                echo '</form></tr>';
                                            }
                                        }
                                        ?>
                </tbody>
              </table>
              <center>
                <button class="btn btn-success"  name="addAllTitelToPlst">Agregar Todo</button>
              </center>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<?php require __DIR__ . '/../footer.phtml' ?>