<?php
/**
 *  Ecast
 */
?>

<div class="content-wrapper">
  <section class="content">
    <div class="row">
      <div class="col-xs-8">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"><i class="fa fa-list"></i> Archivos Mp3</h3>
          </div>
          <div class="box-body table-responsive no-padding">
            <form method="post" action="/archivos/playlist">
              <table class="table table-hover" id="example">
                <thead>
                  <tr>
                    <th>Playlist</th>
                    <th>Numero de Canciones</th>
                    <th>Tiempo</th>
                    <th>Accion</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                                        $results = DB::query("SELECT * FROM playlist WHERE user_id=%s", $_SESSION['account_id']);
                                        foreach ($results as $row) {
                                            echo '<tr><form action="/archivos/playlist" method="post">';
                                            echo "<td>" . $row['playlist_name'] . "</td> \n";
                                            DB::query("SELECT * FROM playlist_mp3_rel WHERE playlist_id=%s", $row['id']);
                                            $counter = DB::count();
                                            echo "<td>" . $counter . "</td> \n";
                                            echo "<td> </td> \n";
                                            echo '<td>'; ?>
                <button class="btn btn-warning" value="<?= $row['id'] ?>" name="editPlaylst" ><img src="/image/fuge/pencil.png" ></button>
                <button name="delPlaylst" value="<?= $row['id']?>" class="btn btn-danger" ><img src="/image/fuge/cross-circle.png"></button>
                  </td>
                
                <?php
                                            echo '</form></tr>';
                                        }
                                        ?>
                  </tbody>
                
              </table>
            </form>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"><i class="fa fa-list"></i> Agregar Playlist</h3>
          </div>
          <div class="box-body table-responsive no-padding">
            <form method="post" action="/archivos/playlist">
              <input type="text" name="playlist_name" value=""/>
              <input type="submit" name="addplaylst" id="submit_id" value="Agregar"/>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<?php require __DIR__ . '/../footer.phtml' ?>