 
    <div id="content">
    <div class="container">
        <div class="row">
            <div class="span8">
                <div id="control" class="widget widget-form">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-pencil"></i>
                            <?= _('Lizenzinformation'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <form class="form-horizontal">
                            <fieldset>
                                <div class="control-group">
                                    <label class="control-label" for="disabledInput"><?= _('Lizenzinhaber'); ?></label>

                                    <div class="controls">
                                        <input class="input-large disabled" id="disabledInput" type="text"
                                               placeholder="@KDNAME@" disabled="">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="disabledInput"><?= _('Lizenz-ID'); ?></label>

                                    <div class="controls">
                                        <input class="input-xxlarge disabled" id="disabledInput" type="text"
                                               placeholder="@RECHNR@" disabled="">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="disabledInput"><?= _('Mail'); ?></label>

                                    <div class="controls">
                                        <input class="input-large disabled" id="disabledInput" type="text"
                                               placeholder="@KDMAIL@" disabled="">
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /.widget -->
            </div>
            <!-- /span8 -->
            <div class="span4">
                <div id="formToc" class="widget highlight">
                    <div class="widget-header">
                        <h3><?= _('S:P Lizenz Informationen'); ?></h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <p>
                            <?= _('Informationen zur'); ?>
                            <a href="http://login.streamerspanel.de/user/terms" target="_blank"><?= _('LIZENZ') ?></a>
                        </p>
                        <br>

                        <p>
                        </p>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /.span4 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>