 
<?php require __DIR__ . '/../header.phtml' ?>

<div style="width:500px" class="wmfg_layout_1">

    <form method="post" action="/benutzerverwaltung/del">

        <ul class="wmfg_questions">

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Kundennummer') ?></label>
                <input type="text" class="wmfg_text" name="kundennummer" id="text_id"
                       value="<?php echo $account['kundennummer'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Passwort') ?></label>
                <input type="text" class="wmfg_text" name="password" id="text_id"
                       value="<?php echo $account['password'] ?>"/>
            </li>


            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Vorname') ?><br></label>
                <input type="text" class="wmfg_text" name="vorname" id="text_id"
                       value="<?php echo $account['vorname'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Nachname') ?><br></label>
                <input type="text" class="wmfg_text" name="nachname" id="text_id"
                       value="<?php echo $account['nachname'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Straße') ?></label>
                <input type="text" class="wmfg_text" name="straße" id="text_id"
                       value="<?php echo $account['straße'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Hausnummer') ?></label>
                <input type="text" class="wmfg_text" name="hausnummer" id="text_id"
                       value="<?php echo $account['hausnummer'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Ort') ?></label>
                <input type="text" class="wmfg_text" name="ort" id="text_id" value="<?php echo $account['ort'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('PLZ') ?></label>
                <input type="text" class="wmfg_text" name="plz" id="text_id" value="<?php echo $account['plz'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Tel.') ?></label>
                <input type="text" class="wmfg_text" name="telefon" id="text_id"
                       value="<?php echo $account['telefon'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('Handy') ?></label>
                <input type="text" class="wmfg_text" name="handy" id="text_id" value="<?php echo $account['handy'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label" for="text_id"><?= _('E-Mail') ?></label>
                <input type="text" class="wmfg_text" name="mail" id="text_id" value="<?php echo $account['mail'] ?>"/>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label"><?= _('Benutzerrechte') ?></label>
                <table class="wmfg_answers">
                    <tr class="wmfg_a">
                        <td class="wmfg_a_td"><input type="radio" class="wmfg_checkbox" name="usr_grp" id="checkbox_1"
                                                     value="adm"/></td>
                        <td><label class="wmfg_label_a" for="checkbox_1"><?= _('SuperAdmin') ?></label></td>
                    </tr>
                    <tr class="wmfg_a">
                        <td class="wmfg_a_td"><input type="radio" class="wmfg_checkbox" name="usr_grp" id="checkbox_2"
                                                     value="user" checked="checked"/></td>
                        <td><label class="wmfg_label_a" for="checkbox_2"><?= _('Stream-Inhaber') ?></label></td>
                    </tr>
                </table>
            </li>

            <li class="wmfg_q">
                <label class="wmfg_label"><?= _('Benutzer wirklich LÖSCHEN?') ?></label>
                <table class="wmfg_answers">
                    <tr class="wmfg_a">
                        <td class="wmfg_a_td"><input type="radio" class="wmfg_checkbox" name="delUser" id="checkbox_1"
                                                     value="1"</td>
                        <td><label class="wmfg_label_a" for="checkbox_1"><?= _('JA BENUTZER LÖSCHEN') ?></label></td>
                    </tr>
                    <tr class="wmfg_a">
                        <td class="wmfg_a_td"><input type="radio" class="wmfg_checkbox" name="delUser" id="checkbox_2"
                                                     value="0" checked="checked"/></td>
                        <td><label class="wmfg_label_a" for="checkbox_2"><?= _('nein') ?></label></td>
                    </tr>
                </table>
            </li>

            <input type="submit" class="wmfg_btn" name="del" id="submit_id" value="<?= _('LÖSCHEN') ?>"/>

        </ul>

    </form>

</div>
<?php require __DIR__ . '/../footer.phtml' ?>
