<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 4.0.0
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */

?>
    <script>
        $(function () {                       // On DOM ready
            $('#myModal').modal('show');     // Show the modal
        });
    </script>

    <div class="modal fade" id="myModal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3><?php echo _('DJ - Limit setzen'); ?></h3>
            </div>
            <div class="modal-body">
                <td>
                    <form action="/benutzerverwaltung/setdjlimit" method="post">
                        <div class="control-group">
                            <label class="control-label" for="input01"><?= _('DJ-Limit'); ?></label>
                            <div class="controls">
                                <input type="text" class="input-large" name="djlimituser" id="input01">
                            </div>
                        </div>
                        <button class="btn btn-tertiary" name="sendlimit" >Speichern</button>
                    </form>
                </td>
            </div>
            <div class="modal-footer">
            </div>
    </div>
